name: VioTrap
version: '1.1.8'
main: org.migrate1337.viotrap.VioTrap
api-version: '1.16'
softdepend:
  - WorldEdit
  - WorldGuard
  - CombatLogX
  - PvPManager
commands:
  viotrap:
    description: Main VioTrap command
    usage: /viotrap <info|give|skins|createskin|createplateskin|reload>
    aliases: [vt]
